### ISSUE TITLE
About construct level set field using marker particles

### ISSUE THREAD

**Issue by Yihao-Shi** [g1n0st/A-Level-Set-Method-for-Magnetic-Substance-Simulation#2]
hello, could you tell me the reference regarding to  construct level set field using marker particles. Many thanks

**Comment by g1n0st** [comment]
hi, you can refer to the section 8.1 Marker Particles and Voxels of _Fluid Simulation for Computer Graphics, Second Edition_.

**Comment by Yihao-Shi** [comment]
thank you!
